---
# These tasks install http and the php modules.

- name: Install http and php etc
  apt:
    name: ['apache2', 'php', 'php-mysql', 'git']
    state: present
  become: yes

- name: Recursively remove directory
  ansible.builtin.file:
    path: /var/www/html
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'


- name: http service state
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes

